name: CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
        -   cron: '0 16 * * 0' # sunday 16:00
jobs:
    main:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: [ '14.x', '16.x', '17.x' ]
                os: [ ubuntu-latest ]

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2

            -   name: Use Node ${{ matrix.node }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node }}

            -   name: Setup yarn
                run: npm install -g yarn

            -   name: SetupCache
                if: ${{ !env.ACT }}
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            -   name: Install packages
                run: yarn install --no-lockfile
                env:
                    npm_config_build_from_source: true

            -   name: Lint
                run: yarn lint

            -   name: Test
                run: yarn test --ci --coverage --maxWorkers=1
